[package]
name = "analysis"
version = "2.0.0"
edition = "2024"

[dependencies]
roxmltree = "0.21"
tracing = "0.1"
indexmap = "2"
proc-macro2 = { version = "1", optional = true, default-features = false }
quote = { version = "1", optional = true, default-features = false }
syn = { version = "3", optional = true, default-features = false, features = [
    "parsing",
    "full",
] }
heck = "0.5.0"
tinyvec = "1.10.0"

[features]
default = ["rust"]
rust = ["quote", "syn", "proc-macro2"]

[dev-dependencies]
tracing-test = "0.2"
tracing-subscriber = "0.3"
